version: '3.8'

services:
  juice-shop:
    image: bkimminich/juice-shop
    ports:
      - "3000:3000"
    networks:
      - zapnet

  zap:
    image: ictu/zap2docker-weekly
    depends_on:
      - juice-shop
    networks:
      - zapnet
    volumes:
      - ./zap-config:/zap/wrk:ro
      - ./reports:/zap/reports
    command: >
      zap-full-scan.py -t http://juice-shop:3000 -r /zap/reports/zap-report.html -c /zap/wrk/zap-policy.xml

networks:
  zapnet:
    driver: bridge
