name: OWASP ZAP Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Docker Compose (Juice Shop + ZAP)
        run: |
          docker compose up --abort-on-container-exit || echo "ZAP scan completed with findings"

      - name: Ensure write permissions for reports folder
        run: |
          mkdir -p reports
          chmod -R 777 reports

      - name: Upload ZAP Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap/reports/zap-report.html
